### ISSUE TITLE
GNSS data is stored even is Raider processing period is different

### ISSUE THREAD

**Issue by kam3545** [dbekaert/RAiDER#288]
**Describe the bug**
**Copy same input station file in place of specific date station data**

**To Reproduce**
**Command used**
raiderDelay.py --model NCMR --date 20180701 20180731 5 --time 00:00 --station_file /data2/NISAR/DEMO/TEST2/RAiDER/final201807.csv --zref 3000 -v

or
**Example 6. Generate weather model/GNSS residual plots**
raiderDelay.py --model GMAO --date 20190101 20191231 12 --time 00:00 --station_file ../GNSS_2019/gnssStationList_overbbox.csv --zref 30000 -v

**Error Output**
Output station files are of same size in place for specific date
Issue #287

**Expected behavior**
Output station data should for a selected day

**Screenshots**
![Screenshot from 2021-03-11 09-35-28](https://user-images.githubusercontent.com/41619377/110734429-d4402b80-824d-11eb-8bf9-fc6a92f95bb7.png)

**Comment by kam3545** [comment]
@dbekaert please see above issue.

**Comment by dbekaert** [comment]
@kam3545 from your email are you suggesting this issue goes away when you do not specify an "interval" for the temporal range?

**Comment by dbekaert** [comment]
@jlmaurer Can you share your thoughts? 
This item is holding back @kam3545 for NCUM analysis.

**Comment by jlmaurer** [comment]
@dbekaert @kam3545 I'm running the GMAO example command above for the testing sample GNSS data set and I'm not currently getting any errors. The code is still running so it may yet break; however, it appears to be creating and writing the files just fine. Perhaps make sure to pull the latest branch @kam3545 and try again?

**Comment by kam3545** [comment]
@jlmaurer & @dbekaert   Agree, the codes are working fine, I am using recent version of RAiDER. Please check for same issue using below commands.
 
1. Download sample data of GNSS using below commands
**raiderDownloadGNSS.py --download --out products --date 20200101 20200131 --returntime '00:00:00' -b '30 40 -80 -70'**

2. Run Delay calculation with time loop using below command
**raiderDelay.py --model GMAO --date 20200101 20200131 15 --time 00:00 --station_file products/UNRcombinedGPS_ztd.csv --zref 30000 -v**

3. Still, prepare files are for all days of Jan 2020, in place of specific dates (every single day).
Same values are repeat for other days. (attached
[GMAO_Delay_20200101T000000_Zmax30000.0.csv.gz](https://github.com/dbekaert/RAiDER/files/6356546/GMAO_Delay_20200101T000000_Zmax30000.0.csv.gz)
[GMAO_Delay_20200116T000000_Zmax30000.0.csv.gz](https://github.com/dbekaert/RAiDER/files/6356547/GMAO_Delay_20200116T000000_Zmax30000.0.csv.gz)
[GMAO_Delay_20200131T000000_Zmax30000.0.csv.gz](https://github.com/dbekaert/RAiDER/files/6356548/GMAO_Delay_20200131T000000_Zmax30000.0.csv.gz)

)

Thanks

**Comment by jlmaurer** [comment]
@kam3545 ah I see what the problem is. The file that gets generated with the GNSS delays has all the dates in it, so when you do the calculation in RAiDER you end up simply concatenating all the delays for (what is actually) one day only to all of the dates available in the file. So, products/UNRcombinedGPS_ztd.csv contains multiple dates. You should use instead the file products/gnssStationList_overbbox.csv, which is the list of unique stations. 

While this is not a bug (in the sense that it is intended behavior), it is worth thinking whether we should remove extra rows when producing the delay results, if a user passes a file with multiple days. There is no computation overhead (unless the number of days is large, in which case the merge might take awhile), but still is confusing because e.g. there are also dates in the file that are not associated with the actual date of the RAiDER delays. @dbekaert @sssangha any thoughts?

**Comment by dbekaert** [comment]
@jlmaurer We write out a new file if i remember the code correctly where we combine the GNSS and the Raider outputs. I suggest we only copy over the relevant gnss data in the file upon creation that intersects with the raider data time-period constrains, period sampling, and utc.

**Comment by dbekaert** [comment]
take unique value of station list prior to running delay calculation in RAiDER.
