### ISSUE TITLE
Automated support for ARIA/HYP3 products

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#404]
We need a wrapper that reads a GUNW and generates the correct config file.

From the GUNW we would fetch:
- wavelength
- time
- reference and secondary dates
- cubes for los
- orbit if needed [download on fly?]
- left or right looking

The user input would then just be: 
- zenith, slant, or slant ray-tracing [possibly force one?]
- model type
- output format

**Comment by dbekaert** [comment]
@jlmaurer @bbuzz31 suggest we capture the proposed implementation here too.

**Comment by jlmaurer** [comment]
@dbekaert @bbuzz31 `prepARIA` gets us partway there already, but one thing we might consider is the use of a __main__.py to have a single CLI interface with run_steps specified instead of having multiple CLI programs. I started implementing one (#405) and I think with the exception of raiderStats it would be pretty straightforward. This is also @jhkennedy 's idea. This would make things potentially cleaner than having to call a separate CLI for first grabbing data from the GUNW then calling raiderDelay, which is what is done currrently with prepARIA.

**Comment by dbekaert** [comment]
Can you add more information as to what the expected calls would look like
under that scenario?

**Comment by cmarshak** [comment]
Also, based on a discussion with @jhkennedy today, its likely there will be a few workflows that will need to be supported possibly by a CLI.

As a preference, rather than writing a lot of control flow, it might be easier to have different entry points within a CLI to distill the script as much as possible and make raider's library shine and illustrate how others can generate their own workflows from the library as well.

[Here](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/dev/isce2_topsapp/__main__.py#L199-L204) is what the GUNW processing does (written by Forrest and Joe) and the discussion from Joe [here](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/73) see "on entry points".

**Comment by bbuzz31** [comment]
Here are options for GUNW support... Option 1 is more in line with what we discussed, but I think Option 2 is cleaner

### Option 1:

- A stand alone prepFromARIA command line script with the following options

```
usage: prepFromAria.py [-h] [--model MODEL] [--write] [--format FMT] [files]
	
	Prepare files from ARIA-tools output to use with RAiDER
	
	positional arguments:
	  files                 ARIA GUNW netcdf files (accepts single file and wildcard matching)
	
	options:
	  -h, --help            show this help message and exit
	  --model MODEL, -m MODEL
	                        Weather model (default=HRRR)
	  --write, -w           Optionally write the delays into the GUNW products
	  --format FMT, -t FMT  Output file format (default=tif)
```

- This could be called by a user directly
- This could be called by hyp3 using the trick with the entrypoints trick
-  E.g., ` '++process', choices=['prepFromAria', 'calc_delays'], default='calc_delays',`

**Drawbacks**:
1. Confusing. The `++process` flag would imply it's a separate workflow from calculating delays, but it's not. `calc_delays` would still be required. 
2. Confusing wrt the lack of config file for inexperienced users.
3. Seems unnecessary to expose another script.

	
### Option 2:
- Always use the config file 
    - add group to YAML with directory of netcdfs and write flag
- Don't give prepFromAria it's own CLI, just make it a library, and pass the config file arguments to it
- Can set HYP3 defaults in the config (HRRR … )

	
**Drawbacks**:
1. Have to think about writing out the actual yaml that get's used and if we want to overwrite (potentiallly have a ton of yamls)
2. May need a function for HYP3 to write the GUNW into the config file

**Comment by jhkennedy** [comment]
For the subprocessor trick (using a `++process` to call different entry_points), I would expect them to generally be fully end-to-end workflows, so I would expect an argument like `++process aria` to run `prepFromAria.py` and then `calc_delays` after. 

Instead of entrypoints like that, there could also be a subprocessor, that'd look something like:
```
$ raider aria <args>
$ raider deleys <args>
```

And when I think of library-first development, I'm generally arguing for a structure like:

Python module:
```python
def some_process(*args, **kwargs):
    ...
    
def main():  # Takes no arguments!
    parser = arparse.ArgumentParser(...)
    # add args
    args = parser.parse_args()
    
    some_process(**args)
```

pyproject.toml:
```toml
[project.scripts]
"some_process" = "package.module:main"
```

So, the `main` argument is *only* responsible for wrapping CLI arguments around the actual "work" function, which can equally be called from python/notebooks and you get the same results. The CLI arguments should match the function arguments *as close as possible*.

**Comment by bbuzz31** [comment]
See Discussion #434
