### ISSUE TITLE
Multiprocessing and Python 3.8 #

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#43]
@leiyangleon saw this here on ISCE forum. Not sure if its relevant but post it here. https://github.com/isce-framework/isce2/issues/146#issue-632619624

**Comment by leiyangleon** [comment]
I think the spawning method (default for macOS) is sufficient for our applications, where child processes only inherit necessary resources from the parent process. For the forking method that is required by dense ampcor and etc. in ISCE, the child processes will inherit everything from the parent process, thus identical to the parent one. The forking method also causes safety issues. So I think we are fine. BTW, I use Python 3.7 and never tested with Python 3.8. If there are problems using Python 3.8, we can use Piyush's way to fix that. Need to confirm with @jlmaurer to see if the use of multiprocessing in interpolation gets impacted with this. I guess not.

**Comment by jlmaurer** [comment]
I agree, this should not be an issue for us because when developing the code I never assume that the parent data is passed to the child process, which is what forking assumes. I.e., spawning a new process results in a child that doesn't remember its parents' possessions (see [this](https://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/) older article and also the [documentation page](https://docs.python.org/3/library/multiprocessing.html)).
