### ISSUE TITLE
[BUG] Multiple dates incorrectly read

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#456]
To reproduce, make a config file with two dates: 
`date_group:
    date_list: (20200130, 20200124)
`

What happens is that the weather model objects gets instantiated with an empty `files` attribute so the first if block gets activated below and the weather model gets downloaded if it exists or reused.
Either way it then gets added to the `files` attribute. The delays are calculated, and the loop continues to the next date. Now the previous date is exists in `files` so the if block is skipped and the previous date is  reused to calculated delays at new date.

```
 download_flag = True
    if weather_model.files is None:
        weather_model.filename(time, wmLoc)
        if os.path.exists(weather_model.files[0]):
            if not force_download:
                logger.warning(
                    'Weather model already exists, please remove it ("%s") if you want '
                    'to download a new one.', weather_model.files
                )
                download_flag = False
    else:
        download_flag = False
```

`processWM.py`

**Comment by jlmaurer** [comment]
@bbuzz31 something seems odd about this. A new date should imply that a new weather model object gets instantiated; but if the files attribute is populated clearly that isn't happening. The weather model object from the first date should get destroyed after the for-loop is complete, not passed to the loop again. 

After looking around, I think the problem is [here](https://github.com/dbekaert/RAiDER/blob/a2c6cb66bb6cce2665509be84109e6348bcf3ddb/tools/RAiDER/cli/raider.py#L284). The weather model is getting instantiated prior to the for-loop, but then defined each time within the for-loop, as the same object. This is incorrect behavior I think. We should instead renew the instantiation within the for-loop each time. We should still keep the changes you made in #457 but also add the object renewal. I can push an attempt to fix or you can try, whichever you prefer!
