### ISSUE TITLE
[BUG] Changelog runner fails with HTTP 403 error

### ISSUE THREAD

**Issue by garlic-os** [dbekaert/RAiDER#653]
**Describe the bug**
All runs of `changelog.yml` have failed with an HTTP 403 error since June 8. Unless I am doing something wrong (every commit since then to date has been mine) I don't think anything I am doing should be triggering this kind of error.

**To Reproduce**
1. Make a commit to a pull request on `dev` or `main`
2. Wait for changelog runner to finish
3. Runner fails with HTTP 403 error

**Expected behavior**
As far as I know, the changelog runner should only fail if the pull request does not modify the repo's `CHANGELOG.md`; it at least should not be failing for this reason.

**Screenshots**
![First occurrence of the 403 error on June 8](https://github.com/dbekaert/RAiDER/assets/14845347/32f853b5-8640-40ac-959b-96660dda1f4e)

**Desktop (please complete the following information):**
 - RAiDER upstream/dev v0.5.1 223d86248c70ca50af338a26335b91fce5eb4ac4
 - OS: N/A

**Additional context**
- changelog.yml run log: https://github.com/dbekaert/RAiDER/actions/workflows/changelog.yml
- Last successful run — still failed, but for a valid reason: https://github.com/dbekaert/RAiDER/actions/runs/9357743767
- First 403 error right after: https://github.com/dbekaert/RAiDER/actions/runs/9432235947

**Comment by jhkennedy** [comment]
@garlic-os the [Reusable Changelog Check](https://github.com/ASFHyP3/actions#reusable-changelog-checkyml) action uses [Zomzog/changelog-checker](https://github.com/Zomzog/changelog-checker) under the hood with the default `checkNotification: Detailed`:
> The checkNotification allows switching between Simple and Detailed checks. The simple check is based on the default check of the action. The detailed check will create a second check with a more precise message, but it required write access so it does not work with forks.
>
> Detailed check fallback to simple for forks.

It looks like the action is not falling back appropriately, so that's why you're seeing the 403 Errors. It does seem to still work for non-forks, e.g.:
* https://github.com/ASFHyP3/its-live-monitoring/actions/runs/9323375656

but I do see the 403 failures for dependabot PRs, which shouldn't run the detailed check as they are using a skip label:
* https://github.com/ASFHyP3/hyp3/actions/runs/9472867493/job/26106462418?pr=2321


Notably, [Zomzog/changelog-checker](https://github.com/Zomzog/changelog-checker) is a Node.js 12 action, which is being forced to run on Node.js 16, which is also deprecated and should be running on Node.js 20 now. But the last release was in Sept. 2022, and it hasn't seen a commit on the default branch since Jul. 2023, so we should find an alternative for this action.
