### ISSUE TITLE
Speed-up of downloadgnssdelays.py and statsPlot.py

### ISSUE THREAD

**Issue by sssangha** [dbekaert/RAiDER#66]
**Proposed Enhancement**
Accessing delays from UNR and storing it in a CSV file through ``` downloadgnssdelays.py```,  and thereafter loading this file and prepping it for plotting through ``` statsPlot.py``` is still rather slow and inefficient, especially over a global scale. The latter in my experience can take over a day, while the former can take ~20 mins. 

Specifically, I wish to explore ways to parallelize certain functions where appropriate (e.g. appending delays to a CSV file and splitting data into grid-cells of a given spacing) or perhaps developing more efficient alternatives to existing routines (e.g. plotting maps of delays directly from a pandas dataframe instead of passing a gridded array meant to serve as a pseudo-raster).

**Suggested baseline tests**
Instead of running global/decadal tests to start out, I suggest running jobs over a more moderately scale spanning California and 2 years. 
Specifically as so:
###Generate CSV of delays across all stations spanning California between 2016 and 2018 at 06:00 UTC
```raiderDownloadGNSS.py --out CA_test -y '2016,2018' --returntime '00:06:00' -b '31 42 -125 -113'```

###Generate figures of the station distribution and delay heatmaps
```raiderStats.py -f CA_test/CombinedGPS_ztd.csv -w CA_test/maps -ti '2016-01-01 2018-12-31' -grid_heatmap -station_distribution -grid_delay_mean -grid_delay_stdev -b '31 42 -125 -113'```

PS, sorry for posting a blank ticket earlier. My network went down for a while and it was somehow submitted prematurely.

**Comment by dbekaert** [comment]
@Askaholic Could you provide some thoughts on this enhancement; perhaps identify current bottlenecks that we also should address in the code, caveats of over hammering a website, and perhaps basic profiling on the download and CSV generation?

**Comment by Askaholic** [comment]
Ok, I can take a look at this today.

**Comment by Askaholic** [comment]
@sssangha and I took a look at this together yesterday. We used `cProfile` to figure out that almost all of the time is spent downloading the data with `requests.get`, which is not really surprising. Since the data hosted by UNR is only available through a bog standard Apache2 HTTP file server, we are stuck doing 1 web request per file. So the only real option for speeding it up is doing multiple web requests at a time. Since it required minimal code changes, we did this with a multiprocessing pool, but there would be more efficient ways to do this using asyncio, depending on how much more time we want to spend on that aspect.

**Comment by dbekaert** [comment]
I understand that the current improvement already cut by a factor of 4
@Askaholic Do you have indication on what could be gained versus time spend?

**Comment by Askaholic** [comment]
I think it really just depends on the user's network bandwidth (and the bandwidth of the UNR server). In theory you could download thousands of files at once. What the CPU overhead of forking thousands of processes is, I'm not sure. I would guess you'd start to notice it and you could get better performance using asyncio, but in all likelihood you will run into network bandwidth limitations before you run into CPU limitations due to excessive forking.

@sssangha was going to experiment with bumping the number of concurrent downloads up. I'm not sure what the results of that were.

**Comment by dbekaert** [comment]
Addressed through #72
