### ISSUE TITLE
Fix for LOS file and state vector delay calculations 

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#79]
Fix bug in RaiderDelay option using the LOS option.
- state vector
- LOS file

```
Traceback (most recent call last):
  File "tools/bin/raiderDelay.py", line 20, in <module>
    parseCMD()
  File "/lib/python3.7/site-packages/RAiDER/runProgram.py", line 151, in parseCMD
    outformat, t, out, download_only, verbose, wfn, hfn)
  File "/lib/python3.7/site-packages/RAiDER/delay.py", line 164, in tropo_delay
    lons=lons, los=los, zref=zref, time=time, verbose=verbose, download_only=download_only)
  File "/lib/python3.7/site-packages/RAiDER/processWM.py", line 85, in prepareWeatherModel
    weather_model.load(f, outLats=lats, outLons=lons, los=los, zref=zref)
  File "/lib/python3.7/site-packages/RAiDER/models/weatherModel.py", line 148, in load
    self._runLOS(los, zref, los_flag)
  File "/lib/python3.7/site-packages/RAiDER/models/weatherModel.py", line 200, in _runLOS
    ray_x, ray_y, ray_z = t.transform(ray[..., 0], ray[..., 1], ray[..., 2], always_xy=True)
IndexError: index 1 is out of bounds for axis 4 with size 1
```

This would need to be fixed in order for @Askaholic to continue with refactoring.

**Comment by Askaholic** [comment]
I looked into this a little bit. I think there are actually 2 issues here. The first is that the look vectors returned by Geo2rdr are not correct, which causes `makePoints3D` to return rays of length 1 somehow (for example the shape I was getting was `(587, 519, 41, 3, 1)`). Then the second issue is that the indices into the ray are also not correct because they should be splitting the second to last axis, not the last axis. I can fix the second issue easily, but fixing the statevectors is going to be more difficult.

**Comment by dbekaert** [comment]
@jlmaurer can you add in two unit test for the code, as this was fixed in the past and looks to have sneaked back in:
- for a lon lat on the ground for a know location/S1 path, e.g. MExico, do a wget to an orbit file and retrieve the unit vector using geo2rdr and make sure the numbers are correct and in the right format. Do one for near range and one for far range.
- For the same track which we already have processed provided the LOS file as like 2 pixels (one in near range and one in far range), perhaps approximately the same lon lat location. verify of the unit vector values make sense.

**Comment by jlmaurer** [comment]
@dbekaert sounds good; the whole losreader module needs unit-tested, so I'll work on those.
