### ISSUE TITLE
Code-coverage though Pytest and coveralls

### ISSUE THREAD

**Issue by dbekaert** [dbekaert/RAiDER#80]
Per discussion with @Askaholic:

- it woudl be good to include a coverage report as part of pytest.
This allows us to see how much of the unit-test cover the code; and would highlight gabs.

- adding coveralls as application which would then test the coverage for new code to be added in each PR. It would take the coverage report from the py-test and visualized it in the PR like CircleCI. https://coveralls.io/

**Comment by Askaholic** [comment]
To generate the coverage report we can use https://pypi.org/project/pytest-cov/. This will generate a coverage file which can be optionally posted to coveralls.io, which will give us coverage statuses on PR's and also track coverage changes over time.

Since some of these dependencies are only required for people who are developing the project, typically they would be installed as optional "dev" dependencies, but I'm not sure if conda has facilities to do that. The total needed package list for generating coverage reports and reporting them to coveralls would be:
- pytest-cov (https://pypi.org/project/pytest-cov/)
- coveralls (https://pypi.org/project/coveralls/)

but of course neither of these are needed in order to run RAiDER.

**Comment by dbekaert** [comment]
we can make and environment_dev.yml file, and update circle ci to use that
one. We should just be careful in future to ensure that we update both
files if we expand the requirements.
Does circle ci also not have a coverage reporter?

**Comment by Askaholic** [comment]
Oh yea, maybe it's possible to split the dependencies between two files, that would work nicely as long as Vonda lets you install from multiple environment files. 

I think the coverage reporting is just a web request (file upload?) so technically it can be done with wget or curl, but it’s easier to just let the python script do it.
